### ISSUE TITLE
Add spinner during transitions (was: Improve performance)

### ISSUE THREAD

**Issue by crw** [joyvuu-dave/comeals-rewrite#11]
edit: scratch all that. I think the page just needs a pop-over loading spinner when a "move to next page" button is clicked (like forward/back near the date, or to go to calendar).

~~IMHO page refreshes are too slow for the amount of data being transmitted. Is this a limitation of Heroku? Is there any instrumentation for this?~~

~~One idea would be to run this on the same server as the wiki, see if it is any faster on AWS. The wiki needs a decent-sized server for memory reasons, but barely uses any CPU. I doubt comeals requires much in the way of memory.~~

**Comment by crw** [comment]
Actually, this might be solved by a popover spinner while the next page is loading. That way it feels like the button press did something.

**Comment by joyvuu-dave** [comment]
I've made calendar and meal navigation happen in the background now while maintaining url updates with client side routing. Things should quite a bit snappier now.

**Comment by joyvuu-dave** [comment]
The app is now a full-blown PWA and Redis caches the API calls. At this point, page loads/transitions feel nearly instant.
