### ISSUE TITLE
Increase menu font size

### ISSUE THREAD

**Issue by crw** [joyvuu-dave/comeals-rewrite#14]
The menu font does not need to be as small as it is. Here are a few recent menus, none take anywhere close to the full space:

![screen shot 2017-09-06 at 5 43 10 pm](https://user-images.githubusercontent.com/57712/30140709-4cc966f4-932b-11e7-9517-5e779749e828.png)

![screen shot 2017-09-06 at 5 43 17 pm](https://user-images.githubusercontent.com/57712/30140715-4fe15a40-932b-11e7-955b-3407654e36d9.png)

![screen shot 2017-09-06 at 5 43 25 pm](https://user-images.githubusercontent.com/57712/30140717-51c691cc-932b-11e7-92f1-0ecd6b1f2397.png)

**Comment by joyvuu-dave** [comment]
Increased from 1rem to 1.25rem. While there's still a lot of space in the box, much bigger than that starts to look a little weird in my option.
