### ISSUE TITLE
README: describe how to setup a development environment

### ISSUE THREAD

**Issue by crw** [joyvuu-dave/comeals-rewrite#15]
Requirements? Database?

**Comment by joyvuu-dave** [comment]
Added the basics on how to get the app up and running. Assumes user has experience setting up and running a Rails app on Postgresql.

**Comment by crw** [comment]
What are the requirements for running? Ruby, Postgres, Node, anything else?

**Comment by joyvuu-dave** [comment]
Current requirements are ruby 2.5.1, node 10.7.0, npm 6.1.0, yarn 1.9.2 and a current-ish version of Postgres.

Since the app now separates out the front-end and backend/admin site, these are the requirements for running the later. The UI app requires node, npm and yarn.
