### ISSUE TITLE
Tamao cannot log in

### ISSUE THREAD

**Issue by crw** [joyvuu-dave/comeals-rewrite#16]
Tamao tried the swansway.com and gmail.com email addresses. Does she have an account?

**Comment by joyvuu-dave** [comment]
I had a typo in her account. She should be able to log in w/ tomao@swansway.com now.

**Comment by crw** [comment]
tomao or tamao? edit: I just tested. It looks like it is "tomao@", it should be "tamao@". Note the "a"s.

**Comment by joyvuu-dave** [comment]
Fixed (for real this time).
