### ISSUE TITLE
Entire screen flickers when another user is updating the site

### ISSUE THREAD

**Issue by crw** [joyvuu-dave/comeals-rewrite#17]
Tamao was entering a menu. Although it is cool I was getting live updates (I saw "jalap" turn into "jalapenos") it caused the entire screen to flicker. It seems like rather than update the individual component, which is what React normally does, it thinks the entire page needs to update? 

Seems undesirable but also not a high-priority issue.

**Comment by joyvuu-dave** [comment]
This appears to be fixed.
