### ISSUE TITLE
Google Calendar "share" or export link 

### ISSUE THREAD

**Issue by crw** [joyvuu-dave/comeals-rewrite#21]
Publish the calendar as a Google Shared Calendar. I just did some research and could not find out how this works.

**Comment by joyvuu-dave** [comment]
You can actually already subscribe to the meals you're signed up to eat at or cook for by clicking the subscribe link at the bottom of the calendar page when you're signed in.

**Comment by crw** [comment]
I'm thinking more, the entire calendar. So you could have a calendar overlay which is the comeals calendar on your google, that gets updated when comeals gets updated. 

Maybe the only difference is it shows all meals instead of just subscribed meals? I'll play with it a little, I didn't notice that link.

**Comment by joyvuu-dave** [comment]
Yeah, I thought some people might like to have everything. Laura just wanted to see what she was signed up for. We could have links for both if we made the UI clear.

**Comment by crw** [comment]
I think once you have a user-facing preferences page (with password, etc) you could just show the two links:

All Meals
My Meals & Meals I'm Attending

With Google, at least, it is easy to turn the calendars on and off so I might even subscribe to both simultaneously.

**Comment by joyvuu-dave** [comment]
Just pushed this out. Right now the links are at the bottom of the calendar page.
